### ISSUE TITLE
Your article website appears to have an SSL certificate problem

### ISSUE THREAD

**Issue by mchendricks1** [soofaloofa/swf-starter#3]
A couple of days ago when I first found your article through Google, things worked fine from the browser perspective. And then yesterday, Chrome and Firefox started complaining about insecure connection or something.

https://sookocheff.com/post/aws/getting-started-with-flow-framework/

I would like to make the PayPal donation for your efforts as a token of appreciation.

**Comment by soofaloofa** [comment]
Fixed. Thank you.
